repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: requirements-txt-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        types_or: [python, jupyter]
        args: [
          --fix,
          --select, "I,F,E,W,N"
        ]
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black-jupyter
